# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\PROYECTO CINERAMA\Vistas\CRUDPeli.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_modiSuperUsu(object):
    def setupUi(self, Form_modiSuperUsu):
        Form_modiSuperUsu.setObjectName("Form_modiSuperUsu")
        Form_modiSuperUsu.resize(966, 723)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form_modiSuperUsu.sizePolicy().hasHeightForWidth())
        Form_modiSuperUsu.setSizePolicy(sizePolicy)
        Form_modiSuperUsu.setMinimumSize(QtCore.QSize(966, 723))
        Form_modiSuperUsu.setStyleSheet("")
        self.bgwidget = QtWidgets.QWidget(Form_modiSuperUsu)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 961, 721))
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(75, 166, 214, 255), stop:1 rgba(255, 255, 255, 255));}\n"
"")
        self.bgwidget.setObjectName("bgwidget")
        self.label = QtWidgets.QLabel(self.bgwidget)
        self.label.setGeometry(QtCore.QRect(40, 50, 251, 16))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.bgwidget)
        self.label_4.setGeometry(QtCore.QRect(530, 120, 379, 16))
        self.label_4.setStyleSheet("color: rgb(0,0, 0);")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.bgwidget)
        self.label_6.setGeometry(QtCore.QRect(690, 120, 121, 16))
        self.label_6.setStyleSheet("color: rgb(0,0, 0);")
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(self.bgwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 181, 16))
        self.label_3.setStyleSheet("color: rgb(0,0, 0);")
        self.label_3.setObjectName("label_3")
        self.btnConfirmar = QtWidgets.QPushButton(self.bgwidget)
        self.btnConfirmar.setGeometry(QtCore.QRect(540, 60, 161, 41))
        self.btnConfirmar.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(85, 170, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 1px solid black;\n"
"border-style: outset")
        self.btnConfirmar.setObjectName("btnConfirmar")
        self.tableListUsu = QtWidgets.QTableWidget(self.bgwidget)
        self.tableListUsu.setGeometry(QtCore.QRect(40, 290, 901, 411))
        self.tableListUsu.setStyleSheet("background:rgb(111, 222, 255);\n"
"background:rgb(167, 212, 235);")
        self.tableListUsu.setObjectName("tableListUsu")
        self.tableListUsu.setColumnCount(5)
        self.tableListUsu.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableListUsu.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableListUsu.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableListUsu.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableListUsu.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableListUsu.setHorizontalHeaderItem(4, item)
        self.tableListUsu.verticalHeader().setVisible(False)
        self.boxIdpeli = QtWidgets.QLineEdit(self.bgwidget)
        self.boxIdpeli.setEnabled(False)
        self.boxIdpeli.setGeometry(QtCore.QRect(40, 70, 281, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.boxIdpeli.setFont(font)
        self.boxIdpeli.setStyleSheet("border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 1px solid black;\n"
"color: rgb(0, 170, 255);\n"
"background-color:rgb(213, 196, 208)")
        self.boxIdpeli.setText("")
        self.boxIdpeli.setObjectName("boxIdpeli")
        self.boxTitulo = QtWidgets.QLineEdit(self.bgwidget)
        self.boxTitulo.setGeometry(QtCore.QRect(40, 140, 451, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.boxTitulo.setFont(font)
        self.boxTitulo.setStyleSheet("border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 1px solid black;\n"
"color: rgb(0, 170, 255)")
        self.boxTitulo.setText("")
        self.boxTitulo.setObjectName("boxTitulo")
        self.boxDuracion = QtWidgets.QLineEdit(self.bgwidget)
        self.boxDuracion.setGeometry(QtCore.QRect(520, 140, 141, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.boxDuracion.setFont(font)
        self.boxDuracion.setStyleSheet("border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 1px solid black;\n"
"color: rgb(0, 170, 255)")
        self.boxDuracion.setText("")
        self.boxDuracion.setObjectName("boxDuracion")
        self.label_8 = QtWidgets.QLabel(self.bgwidget)
        self.label_8.setGeometry(QtCore.QRect(300, 10, 321, 31))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.btnSalir = QtWidgets.QPushButton(self.bgwidget)
        self.btnSalir.setGeometry(QtCore.QRect(860, 60, 91, 41))
        self.btnSalir.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(85, 170, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 1px solid black;\n"
"border-style: outset")
        self.btnSalir.setObjectName("btnSalir")
        self.btnEli = QtWidgets.QPushButton(self.bgwidget)
        self.btnEli.setGeometry(QtCore.QRect(710, 60, 141, 41))
        self.btnEli.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(85, 170, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 1px solid black;\n"
"border-style: outset")
        self.btnEli.setObjectName("btnEli")
        self.comboClasi = QtWidgets.QComboBox(self.bgwidget)
        self.comboClasi.setGeometry(QtCore.QRect(690, 141, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboClasi.setFont(font)
        self.comboClasi.setObjectName("comboClasi")
        self.btnNuevo = QtWidgets.QPushButton(self.bgwidget)
        self.btnNuevo.setGeometry(QtCore.QRect(330, 60, 91, 41))
        self.btnNuevo.setMouseTracking(True)
        self.btnNuevo.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(85, 170, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 1px solid black;\n"
"border-style: outset")
        self.btnNuevo.setDefault(False)
        self.btnNuevo.setObjectName("btnNuevo")
        self.boxDirector = QtWidgets.QLineEdit(self.bgwidget)
        self.boxDirector.setGeometry(QtCore.QRect(40, 200, 451, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.boxDirector.setFont(font)
        self.boxDirector.setStyleSheet("border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 1px solid black;\n"
"color: rgb(0, 170, 255)")
        self.boxDirector.setText("")
        self.boxDirector.setObjectName("boxDirector")
        self.label_5 = QtWidgets.QLabel(self.bgwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 180, 181, 16))
        self.label_5.setStyleSheet("color: rgb(0,0, 0);")
        self.label_5.setObjectName("label_5")
        self.btnGrabaNueva = QtWidgets.QPushButton(self.bgwidget)
        self.btnGrabaNueva.setGeometry(QtCore.QRect(430, 60, 91, 41))
        self.btnGrabaNueva.setMouseTracking(True)
        self.btnGrabaNueva.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(85, 170, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 1px solid black;\n"
"border-style: outset")
        self.btnGrabaNueva.setDefault(False)
        self.btnGrabaNueva.setObjectName("btnGrabaNueva")

        self.retranslateUi(Form_modiSuperUsu)
        QtCore.QMetaObject.connectSlotsByName(Form_modiSuperUsu)

    def retranslateUi(self, Form_modiSuperUsu):
        _translate = QtCore.QCoreApplication.translate
        Form_modiSuperUsu.setWindowTitle(_translate("Form_modiSuperUsu", "Form"))
        self.label.setText(_translate("Form_modiSuperUsu", "CODIGO PELICULA"))
        self.label_4.setText(_translate("Form_modiSuperUsu", "DURACION"))
        self.label_6.setText(_translate("Form_modiSuperUsu", "CLASIFICACION"))
        self.label_3.setText(_translate("Form_modiSuperUsu", "TITULO"))
        self.btnConfirmar.setToolTip(_translate("Form_modiSuperUsu", "Presione despues de modificar los datos"))
        self.btnConfirmar.setText(_translate("Form_modiSuperUsu", "MODIFICAR"))
        item = self.tableListUsu.horizontalHeaderItem(0)
        item.setText(_translate("Form_modiSuperUsu", "Codigo Peli"))
        item = self.tableListUsu.horizontalHeaderItem(1)
        item.setText(_translate("Form_modiSuperUsu", "Titulo"))
        item = self.tableListUsu.horizontalHeaderItem(2)
        item.setText(_translate("Form_modiSuperUsu", "Director"))
        item = self.tableListUsu.horizontalHeaderItem(3)
        item.setText(_translate("Form_modiSuperUsu", "Duracion"))
        item = self.tableListUsu.horizontalHeaderItem(4)
        item.setText(_translate("Form_modiSuperUsu", "Clasificacion"))
        self.label_8.setText(_translate("Form_modiSuperUsu", "Gestion de Peliculas"))
        self.btnSalir.setText(_translate("Form_modiSuperUsu", "SALIR"))
        self.btnEli.setText(_translate("Form_modiSuperUsu", "ELIMINAR"))
        self.btnNuevo.setToolTip(_translate("Form_modiSuperUsu", "Presione para crear una nueva Pelicula"))
        self.btnNuevo.setText(_translate("Form_modiSuperUsu", "NUEVA"))
        self.label_5.setText(_translate("Form_modiSuperUsu", "DIRECTOR"))
        self.btnGrabaNueva.setToolTip(_translate("Form_modiSuperUsu", "Presione para grabar la nueva Pelicula"))
        self.btnGrabaNueva.setText(_translate("Form_modiSuperUsu", "GRABA"))
