# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\PROYECTO CINERAMA\Vistas\modiUsuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_modiUsuario(object):
    def setupUi(self, Form_modiUsuario):
        Form_modiUsuario.setObjectName("Form_modiUsuario")
        Form_modiUsuario.resize(917, 636)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form_modiUsuario.sizePolicy().hasHeightForWidth())
        Form_modiUsuario.setSizePolicy(sizePolicy)
        Form_modiUsuario.setMinimumSize(QtCore.QSize(883, 616))
        Form_modiUsuario.setStyleSheet("")
        self.bgwidget = QtWidgets.QWidget(Form_modiUsuario)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 1091, 721))
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 158, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.bgwidget.setObjectName("bgwidget")
        self.box_dni = QtWidgets.QTextEdit(self.bgwidget)
        self.box_dni.setGeometry(QtCore.QRect(40, 60, 431, 31))
        self.box_dni.setObjectName("box_dni")
        self.boxEdad = QtWidgets.QTextEdit(self.bgwidget)
        self.boxEdad.setGeometry(QtCore.QRect(40, 210, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.boxEdad.setFont(font)
        self.boxEdad.setObjectName("boxEdad")
        self.label = QtWidgets.QLabel(self.bgwidget)
        self.label.setGeometry(QtCore.QRect(40, 40, 379, 16))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.boxApellido = QtWidgets.QTextEdit(self.bgwidget)
        self.boxApellido.setGeometry(QtCore.QRect(330, 140, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.boxApellido.setFont(font)
        self.boxApellido.setObjectName("boxApellido")
        self.label_2 = QtWidgets.QLabel(self.bgwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 190, 379, 16))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.bgwidget)
        self.label_4.setGeometry(QtCore.QRect(330, 120, 379, 16))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.bgwidget)
        self.label_5.setGeometry(QtCore.QRect(610, 120, 379, 16))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.bgwidget)
        self.label_7.setGeometry(QtCore.QRect(610, 190, 379, 16))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.boxNombre = QtWidgets.QTextEdit(self.bgwidget)
        self.boxNombre.setGeometry(QtCore.QRect(40, 140, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.boxNombre.setFont(font)
        self.boxNombre.setObjectName("boxNombre")
        self.label_6 = QtWidgets.QLabel(self.bgwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 190, 379, 16))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.boxEmail = QtWidgets.QTextEdit(self.bgwidget)
        self.boxEmail.setGeometry(QtCore.QRect(610, 140, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.boxEmail.setFont(font)
        self.boxEmail.setObjectName("boxEmail")
        self.boxTipo = QtWidgets.QTextEdit(self.bgwidget)
        self.boxTipo.setGeometry(QtCore.QRect(610, 210, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.boxTipo.setFont(font)
        self.boxTipo.setObjectName("boxTipo")
        self.label_3 = QtWidgets.QLabel(self.bgwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 379, 16))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.btnConfirmar = QtWidgets.QPushButton(self.bgwidget)
        self.btnConfirmar.setGeometry(QtCore.QRect(360, 260, 161, 41))
        self.btnConfirmar.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(85, 170, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 3px solid black")
        self.btnConfirmar.setObjectName("btnConfirmar")
        self.btnBuscar = QtWidgets.QPushButton(self.bgwidget)
        self.btnBuscar.setGeometry(QtCore.QRect(500, 50, 161, 41))
        self.btnBuscar.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(85, 170, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 2px solid black;\n"
"box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1);")
        self.btnBuscar.setObjectName("btnBuscar")
        self.tableListUsu = QtWidgets.QTableWidget(self.bgwidget)
        self.tableListUsu.setGeometry(QtCore.QRect(130, 320, 661, 281))
        self.tableListUsu.setObjectName("tableListUsu")
        self.tableListUsu.setColumnCount(5)
        self.tableListUsu.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableListUsu.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableListUsu.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableListUsu.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableListUsu.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableListUsu.setHorizontalHeaderItem(4, item)
        self.boxPass = QtWidgets.QLineEdit(self.bgwidget)
        self.boxPass.setGeometry(QtCore.QRect(320, 210, 251, 31))
        self.boxPass.setObjectName("boxPass")

        self.retranslateUi(Form_modiUsuario)
        QtCore.QMetaObject.connectSlotsByName(Form_modiUsuario)

    def retranslateUi(self, Form_modiUsuario):
        _translate = QtCore.QCoreApplication.translate
        Form_modiUsuario.setWindowTitle(_translate("Form_modiUsuario", "Form"))
        self.box_dni.setHtml(_translate("Form_modiUsuario", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Ingrese DNI a buscar</span></p></body></html>"))
        self.boxEdad.setHtml(_translate("Form_modiUsuario", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.label.setText(_translate("Form_modiUsuario", "DNI"))
        self.boxApellido.setHtml(_translate("Form_modiUsuario", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.label_2.setText(_translate("Form_modiUsuario", "Contraseña"))
        self.label_4.setText(_translate("Form_modiUsuario", "APELLIDO"))
        self.label_5.setText(_translate("Form_modiUsuario", "E-MAIL"))
        self.label_7.setText(_translate("Form_modiUsuario", "TIPO"))
        self.boxNombre.setHtml(_translate("Form_modiUsuario", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.label_6.setText(_translate("Form_modiUsuario", "EDAD"))
        self.boxEmail.setHtml(_translate("Form_modiUsuario", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.boxTipo.setHtml(_translate("Form_modiUsuario", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("Form_modiUsuario", "NOMBRE"))
        self.btnConfirmar.setText(_translate("Form_modiUsuario", "MODIFICAR"))
        self.btnBuscar.setText(_translate("Form_modiUsuario", "BUSCAR"))
        item = self.tableListUsu.horizontalHeaderItem(0)
        item.setText(_translate("Form_modiUsuario", "Dni"))
        item = self.tableListUsu.horizontalHeaderItem(1)
        item.setText(_translate("Form_modiUsuario", "Nombre"))
        item = self.tableListUsu.horizontalHeaderItem(2)
        item.setText(_translate("Form_modiUsuario", "Apellido"))
        item = self.tableListUsu.horizontalHeaderItem(3)
        item.setText(_translate("Form_modiUsuario", "Mail"))
        item = self.tableListUsu.horizontalHeaderItem(4)
        item.setText(_translate("Form_modiUsuario", "Edad"))
