# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\PROYECTO CINERAMA\Vistas\modiSuperUsu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_modiSuperUsu(object):
    def setupUi(self, Form_modiSuperUsu):
        Form_modiSuperUsu.setObjectName("Form_modiSuperUsu")
        Form_modiSuperUsu.resize(966, 723)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form_modiSuperUsu.sizePolicy().hasHeightForWidth())
        Form_modiSuperUsu.setSizePolicy(sizePolicy)
        Form_modiSuperUsu.setMinimumSize(QtCore.QSize(966, 723))
        Form_modiSuperUsu.setStyleSheet("")
        self.bgwidget = QtWidgets.QWidget(Form_modiSuperUsu)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 961, 721))
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(75, 166, 214, 255), stop:1 rgba(255, 255, 255, 255));}\n"
"")
        self.bgwidget.setObjectName("bgwidget")
        self.label = QtWidgets.QLabel(self.bgwidget)
        self.label.setGeometry(QtCore.QRect(40, 50, 251, 16))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.bgwidget)
        self.label_4.setGeometry(QtCore.QRect(330, 120, 379, 16))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.bgwidget)
        self.label_5.setGeometry(QtCore.QRect(310, 200, 379, 16))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.bgwidget)
        self.label_7.setGeometry(QtCore.QRect(570, 120, 121, 16))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.bgwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 200, 121, 16))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(self.bgwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 379, 16))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.btnConfirmar = QtWidgets.QPushButton(self.bgwidget)
        self.btnConfirmar.setGeometry(QtCore.QRect(500, 60, 161, 41))
        self.btnConfirmar.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(85, 170, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 1px solid black;\n"
"border-style: outset")
        self.btnConfirmar.setObjectName("btnConfirmar")
        self.btnBuscar = QtWidgets.QPushButton(self.bgwidget)
        self.btnBuscar.setGeometry(QtCore.QRect(390, 60, 91, 41))
        self.btnBuscar.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(85, 170, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 1px solid black;\n"
"border-style: outset")
        self.btnBuscar.setObjectName("btnBuscar")
        self.tableListUsu = QtWidgets.QTableWidget(self.bgwidget)
        self.tableListUsu.setGeometry(QtCore.QRect(130, 320, 771, 301))
        self.tableListUsu.setStyleSheet("background:rgb(111, 222, 255);\n"
"background:rgb(167, 212, 235);")
        self.tableListUsu.setObjectName("tableListUsu")
        self.tableListUsu.setColumnCount(6)
        self.tableListUsu.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableListUsu.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableListUsu.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableListUsu.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableListUsu.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableListUsu.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableListUsu.setHorizontalHeaderItem(5, item)
        self.box_dni = QtWidgets.QLineEdit(self.bgwidget)
        self.box_dni.setGeometry(QtCore.QRect(40, 70, 341, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.box_dni.setFont(font)
        self.box_dni.setStyleSheet("border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 1px solid black;\n"
"color: rgb(0, 170, 255)")
        self.box_dni.setObjectName("box_dni")
        self.boxNombre = QtWidgets.QLineEdit(self.bgwidget)
        self.boxNombre.setGeometry(QtCore.QRect(40, 140, 241, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.boxNombre.setFont(font)
        self.boxNombre.setStyleSheet("border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 1px solid black;\n"
"color: rgb(0, 170, 255)")
        self.boxNombre.setText("")
        self.boxNombre.setObjectName("boxNombre")
        self.boxApellido = QtWidgets.QLineEdit(self.bgwidget)
        self.boxApellido.setGeometry(QtCore.QRect(320, 140, 221, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.boxApellido.setFont(font)
        self.boxApellido.setStyleSheet("border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 1px solid black;\n"
"color: rgb(0, 170, 255)")
        self.boxApellido.setText("")
        self.boxApellido.setObjectName("boxApellido")
        self.boxEmail = QtWidgets.QLineEdit(self.bgwidget)
        self.boxEmail.setGeometry(QtCore.QRect(310, 220, 341, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.boxEmail.setFont(font)
        self.boxEmail.setStyleSheet("border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 1px solid black;\n"
"color: rgb(0, 170, 255)")
        self.boxEmail.setText("")
        self.boxEmail.setObjectName("boxEmail")
        self.boxEdad = QtWidgets.QLineEdit(self.bgwidget)
        self.boxEdad.setGeometry(QtCore.QRect(40, 220, 241, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.boxEdad.setFont(font)
        self.boxEdad.setStyleSheet("border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 1px solid black;\n"
"color: rgb(0, 170, 255)")
        self.boxEdad.setText("")
        self.boxEdad.setObjectName("boxEdad")
        self.boxTipo = QtWidgets.QLineEdit(self.bgwidget)
        self.boxTipo.setGeometry(QtCore.QRect(570, 140, 51, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.boxTipo.setFont(font)
        self.boxTipo.setStyleSheet("border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 1px solid black;\n"
"color: rgb(0, 170, 255)")
        self.boxTipo.setText("")
        self.boxTipo.setObjectName("boxTipo")
        self.label_8 = QtWidgets.QLabel(self.bgwidget)
        self.label_8.setGeometry(QtCore.QRect(300, 10, 321, 31))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.btnSalir = QtWidgets.QPushButton(self.bgwidget)
        self.btnSalir.setGeometry(QtCore.QRect(840, 60, 111, 41))
        self.btnSalir.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(85, 170, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 1px solid black;\n"
"border-style: outset")
        self.btnSalir.setObjectName("btnSalir")
        self.btnEli = QtWidgets.QPushButton(self.bgwidget)
        self.btnEli.setGeometry(QtCore.QRect(670, 60, 161, 41))
        self.btnEli.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(85, 170, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 1px solid black;\n"
"border-style: outset")
        self.btnEli.setObjectName("btnEli")
        self.label_9 = QtWidgets.QLabel(self.bgwidget)
        self.label_9.setGeometry(QtCore.QRect(630, 150, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: black;")
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Form_modiSuperUsu)
        QtCore.QMetaObject.connectSlotsByName(Form_modiSuperUsu)

    def retranslateUi(self, Form_modiSuperUsu):
        _translate = QtCore.QCoreApplication.translate
        Form_modiSuperUsu.setWindowTitle(_translate("Form_modiSuperUsu", "Form"))
        self.label.setText(_translate("Form_modiSuperUsu", "DNI"))
        self.label_4.setText(_translate("Form_modiSuperUsu", "APELLIDO"))
        self.label_5.setText(_translate("Form_modiSuperUsu", "E-MAIL"))
        self.label_7.setText(_translate("Form_modiSuperUsu", "TIPO"))
        self.label_6.setText(_translate("Form_modiSuperUsu", "EDAD"))
        self.label_3.setText(_translate("Form_modiSuperUsu", "NOMBRE"))
        self.btnConfirmar.setText(_translate("Form_modiSuperUsu", "MODIFICAR"))
        self.btnBuscar.setText(_translate("Form_modiSuperUsu", "BUSCAR"))
        item = self.tableListUsu.horizontalHeaderItem(0)
        item.setText(_translate("Form_modiSuperUsu", "Dni"))
        item = self.tableListUsu.horizontalHeaderItem(1)
        item.setText(_translate("Form_modiSuperUsu", "Nombre"))
        item = self.tableListUsu.horizontalHeaderItem(2)
        item.setText(_translate("Form_modiSuperUsu", "Apellido"))
        item = self.tableListUsu.horizontalHeaderItem(3)
        item.setText(_translate("Form_modiSuperUsu", "Mail"))
        item = self.tableListUsu.horizontalHeaderItem(4)
        item.setText(_translate("Form_modiSuperUsu", "Edad"))
        item = self.tableListUsu.horizontalHeaderItem(5)
        item.setText(_translate("Form_modiSuperUsu", "Tipo"))
        self.box_dni.setText(_translate("Form_modiSuperUsu", "Ingrese DNI a buscar"))
        self.label_8.setText(_translate("Form_modiSuperUsu", "Gestion de Usuarios"))
        self.btnSalir.setText(_translate("Form_modiSuperUsu", "SALIR"))
        self.btnEli.setText(_translate("Form_modiSuperUsu", "ELIMINAR"))
        self.label_9.setText(_translate("Form_modiSuperUsu", "1-Admin    0- Usuario"))
